= Java General Transit Feed Specification (GTFS) Neo4j Importer
v1.2, 2016-02-15
:library: Asciidoctor
:idprefix:
:numbered:
:imagesdir: images
:toc: manual
:css-signature: demo
:toc-placement: preamble
:toc:
:icons: font
:source-highlighter: prettify
:project_id: neo4j-gtfs
:sectanchors:

---

== Project Overview

This project is a showcase of spring-data, neo4j, rest and hateoas.

The Spring Boot based application imports General Transit Feed Specification (GTFS) data from NJTransit into Neo4j
and provides web services to interact with the data.

You need an account as an NJ transit developer.
You can sign up https://www.njtransit.com/mt/mt_servlet.srv?hdnPageAction=MTDevLoginTo[here].

This project is largely derived off the work that was done by  :
http://blog.bruggen.com/p/about-author.html[Rick Van Bruggen] (github account https://github.com/rvanbruggen[rvanbruggen])

Loading the data is based off his blog entry http://blog.bruggen.com/2015/11/loading-general-transport-feed-spec.html["Loading General Transport Feed Spec (GTFS) files into Neo4j - part 1/2"]

Querying the data is based off his blog entry http://blog.bruggen.com/2015/11/querying-gtfs-data-using-neo4j-23-part.html["Querying GTFS data - using Neo4j 2.3 - part 2/2"]

== What you'll build

You will import GTFS files into Neo4j's NoSQL graph-based database from New Jersey Transit website using an automated
importer, and access the data via several useful Restful endpoints.

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]

== Standing up a Neo4j server

Before you can build a this application, you need to set up a Neo4j server.

Neo4j has an open source server you can install for free:

On a Mac, just type:

----
$ brew install neo4j
----

Also on a mac, make sure the Neo4j imports folder has proper write permissions.
This should take care of it:

----
chmod g+w /usr/local/Cellar/neo4j/3.1.4/libexec/import/nmbs/
----

For other options, visit https://neo4j.com/download/community-edition/

Once you installed, launch it with it's default settings:

----
$ neo4j start
----

You should see a message like this:

....
Starting Neo4j.
Started neo4j (pid 96416). By default, it is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /usr/local/Cellar/neo4j/3.0.6/libexec/logs/neo4j.log for current status.
....

By default, Neo4j has a username/password of neo4j/neo4j. However, it requires that the new account password be changed. To do so, execute the following command:

----
$ curl -v -u neo4j:neo4j -X POST localhost:7474/user/neo4j/password -H "Content-type:application/json" -d "{\"password\":\"secret\"}"
----

This changes the password from *neo4j* to *secret* (something to NOT DO in production!) With that completed, you should be ready to run this guide.


[[initial]]
== Permissions to access Neo4j and the NJ Transit Website

Neo4j Community Edition requires credentials to access it. This can be configured with a couple properties.
If you want to use the automated GTFS imported from the New Jersey Transit website, provide your credentials here.

["source","java",tab="8",args="--line-range=1-4"]
----
include::complete/src/main/resources/application.properties[lines=1;1..4]
----

This includes the default username `neo4j` and the newly set password `secret` we picked earlier.

WARNING: Do NOT store real credentials in your source repository. Instead, configure them in your runtime using http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[Spring Boot's property overrides].

With this in place, let's load up the data and

== Loading the data

Two endpoints are provided:

* Dowload and import the data fully automated: +
http://localhost:8080/customrest/LoadData

* Import a predownloaded zip file and place it in the same directory as the Spring Boot app server (default filename rail_data.zip).
Then initiate importing it into Neo4j by calling this URL: +
http://localhost:8080/customrest/LoadPrefetched

== Interact with the data via Spring-Data-Rest

By default all the endpoints exposed via spring-data-rest are left in place.
You can traverse through those by accessing the root of the app server:

http://localhost:8080/

== Interact with the data via custom web services

The application also exposes web services hosting custom cypher queries for trip planning.
Currently only one such endpoint exists, and it is purpose built to provide
trip options from one station to another given departer and arrival time criteria:

http://localhost:8080/stoptimes/search/getMyTrips?serviceId=4&origStation=WESTWOOD&origArrivalTimeLow=06:30:00&origArrivalTimeHigh=07:10:00&destStation=HOBOKEN&destArrivalTimeLow=07:00:00&destArrivalTimeHigh=08:00:00&sort=departureTimeInt,asc&projection=TripPlanResult

== Create your own services

Add new queries to the repository com.popameeting.gtfs.neo4j.repository and interact with them via Spring-Data-Rest's
provided web services - if you need the data presented differently see the projections in
com.popameeting.gtfs.neo4j.entity.projection and how they are being used in the URL above.
