---
tags: [spring-data, neo4j]
projects: [spring-data-neo4j]
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: neo4j-gtfs
This project imports GTFS data from NJTransit in Neo4j and provides web services to interact with the data

== What you'll build

You'll use Neo4j's link:/understanding/NoSQL[NoSQL] graph-based data store to build an embedded Neo4j server, store entities and relationships, and develop queries.

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]

== Standing up a Neo4j server

Before you can build a this application, you need to set up a Neo4j server.

Neo4j has an open source server you can install for free:

On a Mac, just type:

----
$ brew install neo4j
----

For other options, visit https://neo4j.com/download/community-edition/

Once you installed, launch it with it's default settings:

----
$ neo4j start
----

You should see a message like this:

....
Starting Neo4j.
Started neo4j (pid 96416). By default, it is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /usr/local/Cellar/neo4j/3.0.6/libexec/logs/neo4j.log for current status.
....

By default, Neo4j has a username/password of neo4j/neo4j. However, it requires that the new account password be changed. To do so, execute the following command:

----
$ curl -v -u neo4j:neo4j -X POST localhost:7474/user/neo4j/password -H "Content-type:application/json" -d "{\"password\":\"secret\"}"
----

This changes the password from *neo4j* to *secret* (something to NOT DO in production!) With that completed, you should be ready to run this guide.


[[initial]]
== Permissions to access Neo4j

Neo4j Community Edition requires credentials to access it. This can be configured with a couple properties.

[source]
----
include::complete/src/main/resources/application.properties[]
----

This includes the default username `neo4j` and the newly set password `secret` we picked earlier.

WARNING: Do NOT store real credentials in your source repository. Instead, configure them in your runtime using http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[Spring Boot's property overrides].

With this in place, let's wire this up and see what it looks like!

