version: '3.8'

services:
  neo4j:
    image: neo4j:4.2.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/z000m123
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      #- NEO4J_dbms_logs_query_enabled=true  # Enable query logging
      #- NEO4J_dbms_logs_query_threshold=0   # Log all queries regardless of duration; set higher to log slower queries only
      #- NEO4J_dbms_logs_query_allocation_logging_enabled=true # Log memory allocation and deallocation in queries
      #- NEO4J_dbms_logs_query_time_logging_enabled=true # Log query execution times
      #- NEO4J_dbms_logs_debug_level=DEBUG   # Set log level to DEBUG (note this can be very verbose)
    volumes:
      - ./neo4jdocker/data:/data
      - ./neo4jdocker/logs:/logs
      - ./neo4jdocker/import:/import
      - ./neo4jdocker/plugins:/plugins
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
  neo4j-gtfs-java:
    #image: sheepkiller/kafka-manager:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_ENVIRONMENT=ai-rag-neo4j

